build:
  name: apiwiz-core-platform-api
  gitURL: 'git@github.com:itorix/apiwiz-core-platform-api.git'
deployment:
  - appName: coreapi
    buildImage: enable
    jarName: cloud-app-0.0.1-SNAPSHOT.jar
    jarLocation: /app/target
    environments:
      - env: local
        branch: feature
        deployFlag: enbale
        approval: disable
        host: 3.128.86.36
        pem: itorix-dev.pem
        configBranch: main
        configRepo: 'git@github.com:itorix/itorix-core-config.git'
        container: disable
        spaceName: NA
        awsCredProfile: NA
      - env: development
        branch: feature
        deployFlag: enbale
        approval: false
        host: NA
        pem: NA
        configBranch: development
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
        container: Yes
        spaceName: dev
        awsCredProfile: devuser
      - env: stage
        branch: develop
        deployFlag: disable
        approval: true
        host: NA
        pem: NA
        configBranch: stage
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
        container: Yes
        spaceName: NA
        awsCredProfile: devuser
      - env: production
        branch: main
        deployFlag: enbale
        approval: true
        host: NA
        pem: NA
        configBranch: main
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
        container: Yes
        spaceName: apiwiz-system
        awsCredProfile: default
  - appName: apimock
    buildImage: enable
    jarLocation: /api-mock-server/target
    jarName: api-mock-server-0.0.1-SNAPSHOT.jar
    environments:
      - env: local
        branch: feature
        container: No
        deployFlag: enbale
        approval: false
        host: 3.128.86.36
        pem: itorix-dev.pem
        configBranch: main
        configRepo: 'git@github.com:itorix/itorix-core-config.git'
        spaceName: NA
        awsCredProfile: NA
      - env: development
        branch: feature
        deployFlag: enbale
        container: Yes
        spaceName: dev
        awsCredProfile: devuser
        approval: false
        host: NA
        pem: NA
        configBranch: development
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
      - env: stage
        branch: develop
        deployFlag: disable
        container: Yes
        spaceName: ''
        awsCredProfile: devuser
        approval: true
        host: NA
        pem: NA
        configBranch: stage
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
      - env: production
        deployFlag: enbale
        branch: main
        container: Yes
        spaceName: apiwiz-system
        awsCredProfile: default
        approval: true
        host: NA
        pem: NA
        configBranch: main
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
  - appName: testsuite
    buildImage: enable
    jarLocation: /test-suite-lib/target
    jarName: test-suite-lib-1.5.10.RELEASE.jar
    environments:
      - env: local
        branch: feature
        deployFlag: enbale
        container: No
        approval: false
        host: 3.128.86.36
        pem: itorix-dev.pem
        configBranch: main
        configRepo: 'git@github.com:itorix/itorix-core-config.git'
        spaceName: NA
        awsCredProfile: NA
      - env: development
        branch: feature
        deployFlag: enbale
        container: Yes
        spaceName: dev
        awsCredProfile: devuser
        approval: false
        host: NA
        pem: NA
        configBranch: development
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
      - env: stage
        branch: develop
        deployFlag: disable
        container: Yes
        spaceName: ''
        awsCredProfile: devuser
        approval: true
        host: NA
        pem: NA
        configBranch: stage
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
      - env: production
        branch: main
        deployFlag: enbale
        container: Yes
        spaceName: apiwiz-system
        awsCredProfile: default
        approval: true
        host: NA
        pem: NA
        configBranch: main
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
  - appName: sso
    buildImage: enable
    jarName: sso-0.0.1-SNAPSHOT.jar
    jarLocation: /sso/target
    environments:
      - env: local
        branch: feature
        deployFlag: enbale
        spaceName: NA
        container: No
        approval: false
        host: 3.128.86.36
        pem: itorix-dev.pem
        configBranch: main
        awsCredProfile: NA
        configRepo: 'git@github.com:itorix/itorix-core-config.git'
      - env: development
        deployFlag: enbale
        branch: feature
        container: Yes
        spaceName: ''
        awsCredProfile: devuser
        approval: false
        host: NA
        pem: NA
        configBranch: development
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
      - env: stage
        branch: develop
        deployFlag: disable
        container: Yes
        spaceName: ''
        awsCredProfile: devuser
        approval: true
        host: NA
        pem: NA
        configBranch: stage
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
      - env: production
        branch: main
        deployFlag: enbale
        container: Yes
        spaceName: apiwiz-system
        awsCredProfile: default
        approval: true
        host: NA
        pem: NA
        configBranch: main
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
  - appName: notification
    buildImage: disable
    jarName: notification-agent-0.0.1.jar
    jarLocation: /notification-agent/target
    environments:
      - env: local
        branch: feature
        container: No
        deployFlag: enbale
        approval: false
        host: 3.128.86.36
        pem: itorix-dev.pem
        configBranch: main
        configRepo: 'git@github.com:itorix/itorix-core-config.git'
        spaceName: NA
        awsCredProfile: NA
      - env: development
        branch: feature
        deployFlag: enbale
        container: Yes
        spaceName: ''
        awsCredProfile: devuser
        approval: false
        host: NA
        pem: NA
        configBranch: development
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
      - env: stage
        branch: develop
        deployFlag: disable
        container: Yes
        spaceName: ''
        awsCredProfile: devuser
        approval: true
        host: NA
        pem: NA
        configBranch: stage
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
      - env: production
        deployFlag: enbale
        branch: main
        container: Yes
        spaceName: apiwiz-system
        awsCredProfile: default
        approval: true
        host: NA
        pem: NA
        configBranch: main
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
  - appName: apimonitor
    buildImage: enable
    jarName: api-monitor-agent-0.0.1.jar
    jarLocation: /api-monitor-agent/target
    environments:
      - env: local
        branch: feature
        deployFlag: enbale
        container: No
        approval: false
        host: 3.128.86.36
        pem: itorix-dev.pem
        configBranch: main
        configRepo: 'git@github.com:itorix/itorix-core-config.git'
        spaceName: NA
        awsCredProfile: NA
      - env: development
        branch: feature
        deployFlag: enbale
        container: Yes
        spaceName: dev
        awsCredProfile: devuser
        approval: false
        host: NA
        pem: NA
        configBranch: development
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
      - env: stage
        branch: develop
        deployFlag: disable
        container: Yes
        spaceName: ''
        awsCredProfile: devuser
        approval: true
        host: NA
        pem: NA
        configBranch: stage
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
      - env: production
        branch: main
        deployFlag: enbale
        container: Yes
        spaceName: apiwiz-system
        awsCredProfile: default
        approval: true
        host: NA
        pem: NA
        configBranch: main
        configRepo: 'git@github.com:itorix/apiwiz-config-repo.git'
