skipLocalDeploy: false

build:
  name: apiwiz-core-platform-api
  gitURL: git@github.com:itorix/apiwiz-core-platform-api.git

deployment:
  type: core  #type can be core, mock or testsuite or sso or notification or monitor

deployLocal:
- env: local
  branch: feature
  approval: false
  host: 3.128.86.36
  pem: itorix-dev.pem
  configBranch: main
  configRepo: git@github.com:itorix/itorix-core-config.git

deployContainer:
- env: development
  branch: feature
  approval: false
  host: NA
  pem: NA
  configBranch: development
  configRepo: git@github.com:itorix/apiwiz-config-repo.git

- env: stage
  branch: develop
  approval: true
  host: NA
  pem: NA
  configBranch: stage
  configRepo: git@github.com:itorix/apiwiz-config-repo.git

- env: production
  branch: main
  approval: false
  host: NA
  pem: NA
  configBranch: main
  configRepo: git@github.com:itorix/apiwiz-config-repo.git
