//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.24 at 04:51:41 PM IST 
//


package com.itorix.apiwiz.performance.coverge.model;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for FlowStatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlowStatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="coverage">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="91"/>
 *               &lt;enumeration value="67"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="24"/>
 *               &lt;enumeration value="71"/>
 *               &lt;enumeration value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="totalPolicies">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="11"/>
 *               &lt;enumeration value="12"/>
 *               &lt;enumeration value="2"/>
 *               &lt;enumeration value="1"/>
 *               &lt;enumeration value="30"/>
 *               &lt;enumeration value="29"/>
 *               &lt;enumeration value="24"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="executedPolicies">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="10"/>
 *               &lt;enumeration value="8"/>
 *               &lt;enumeration value="0"/>
 *               &lt;enumeration value="7"/>
 *               &lt;enumeration value="17"/>
 *               &lt;enumeration value="4"/>
 *               &lt;enumeration value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="flowType">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Fault Rule"/>
 *               &lt;enumeration value="Pre Flow"/>
 *               &lt;enumeration value="Post Flow"/>
 *               &lt;enumeration value="Flow"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlowStat", propOrder = {
    "name",
    "coverage",
    "totalPolicies",
    "executedPolicies",
    "flowType"
})
public class FlowStat implements ToString
{

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String coverage;
    @XmlElement(required = true)
    protected String totalPolicies;
    @XmlElement(required = true)
    protected String executedPolicies;
    @XmlElement(required = true)
    protected String flowType;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverage(String value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the totalPolicies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalPolicies() {
        return totalPolicies;
    }

    /**
     * Sets the value of the totalPolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalPolicies(String value) {
        this.totalPolicies = value;
    }

    /**
     * Gets the value of the executedPolicies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecutedPolicies() {
        return executedPolicies;
    }

    /**
     * Sets the value of the executedPolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecutedPolicies(String value) {
        this.executedPolicies = value;
    }

    /**
     * Gets the value of the flowType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlowType() {
        return flowType;
    }

    /**
     * Sets the value of the flowType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlowType(String value) {
        this.flowType = value;
    }

    public String toString() {
        final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theName;
            theName = this.getName();
            strategy.appendField(locator, this, "name", buffer, theName);
        }
        {
            String theCoverage;
            theCoverage = this.getCoverage();
            strategy.appendField(locator, this, "coverage", buffer, theCoverage);
        }
        {
            String theTotalPolicies;
            theTotalPolicies = this.getTotalPolicies();
            strategy.appendField(locator, this, "totalPolicies", buffer, theTotalPolicies);
        }
        {
            String theExecutedPolicies;
            theExecutedPolicies = this.getExecutedPolicies();
            strategy.appendField(locator, this, "executedPolicies", buffer, theExecutedPolicies);
        }
        {
            String theFlowType;
            theFlowType = this.getFlowType();
            strategy.appendField(locator, this, "flowType", buffer, theFlowType);
        }
        return buffer;
    }

}
