//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.24 at 04:51:41 PM IST 
//


package com.itorix.apiwiz.performance.coverge.model;
import java.io.StringWriter;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.jvnet.jaxb2_commons.lang.ToString;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;


/**
 * <p>Java class for ProxyStatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProxyStatType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="coverage" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="totalPolicies" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="executedPolicies" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="stats" type="{}statsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlRootElement(name = "ProxyStat")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProxyStat", propOrder = {
    "name",
    "coverage",
    "totalPolicies",
    "executedPolicies",
    "stats"
})
public class ProxyStat
    implements ToString
{

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String coverage;
    @XmlElement(required = true)
    protected String totalPolicies;
    @XmlElement(required = true)
    protected String executedPolicies;
    @XmlElement(required = true)
    protected Stats stats;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the coverage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoverage() {
        return coverage;
    }

    /**
     * Sets the value of the coverage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoverage(String value) {
        this.coverage = value;
    }

    /**
     * Gets the value of the totalPolicies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTotalPolicies() {
        return totalPolicies;
    }

    /**
     * Sets the value of the totalPolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTotalPolicies(String value) {
        this.totalPolicies = value;
    }

    /**
     * Gets the value of the executedPolicies property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExecutedPolicies() {
        return executedPolicies;
    }

    /**
     * Sets the value of the executedPolicies property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExecutedPolicies(String value) {
        this.executedPolicies = value;
    }

    /**
     * Gets the value of the stats property.
     * 
     * @return
     *     possible object is
     *     {@link Stats }
     *     
     */
    public Stats getStats() {
        return stats;
    }

    /**
     * Sets the value of the stats property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stats }
     *     
     */
    public void setStats(Stats value) {
        this.stats = value;
    }

    public String toString() {
      /*  final ToStringStrategy strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();*/
    	java.io.StringWriter sw = new StringWriter();
    	JAXBContext jaxbContext = null;
		try {
		jaxbContext = JAXBContext.newInstance(ProxyStat.class);
		Marshaller jaxbMarshaller = jaxbContext.createMarshaller();
		jaxbMarshaller.setProperty(Marshaller.JAXB_ENCODING, "UTF-8");
		jaxbMarshaller.marshal(this, sw);
		} catch (JAXBException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		    return sw.toString();
		
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy strategy) {
        {
            String theName;
            theName = this.getName();
            strategy.appendField(locator, this, "name", buffer, theName);
        }
        {
            String theCoverage;
            theCoverage = this.getCoverage();
            strategy.appendField(locator, this, "coverage", buffer, theCoverage);
        }
        {
            String theTotalPolicies;
            theTotalPolicies = this.getTotalPolicies();
            strategy.appendField(locator, this, "totalPolicies", buffer, theTotalPolicies);
        }
        {
            String theExecutedPolicies;
            theExecutedPolicies = this.getExecutedPolicies();
            strategy.appendField(locator, this, "executedPolicies", buffer, theExecutedPolicies);
        }
        {
            Stats theStats;
            theStats = this.getStats();
            strategy.appendField(locator, this, "stats", buffer, theStats);
        }
        return buffer;
    }

}
